### ISSUE TITLE
[help] can't run the example

### ISSUE THREAD

**Issue by tarzasai** [d0p3t/fivem-js#25]
I just install FiveM server (localhost) & client, then copy all [your javascript example files](https://github.com/d0p3t/fivem-js/tree/master/examples/javascript) in a folder, say `path/to/FiveM/server-data/resources/[local]/twd`, and run `npm install` in it.

At this point I have a new folder, `node_modules`, with just `@citizenfv` and `fivem-js` inside.

Everything looks good when I start the client and connect the server, so in the console I run `start twd`, but I get this:
```
Running build tasks on resource twd - it'll restart once completed.
Error calling system call ref function in resource webpack: Error: Cannot find module 'webpack'
stack:
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\FiveM\server-data\resources\[local]\twd\client.config.js:1:79)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

Now I can make it work by installing webpack in the example folder, but since you didn't put it in the example's package.json I assume it's supposed to use the one under `.../[system]/[builders]`. Or maybe not, I'm really new to FiveM scripting.

PS: server version is "FXServer-master SERVER v1.0.0.1280 win32"

**Comment by d0p3t** [comment]
The examples were recently changed for complete beginners. You should not `npm install` the example resource as indeed the webpack builder that you mentioned should take care of this.

See [__resource.lua](https://github.com/d0p3t/fivem-js/blob/master/examples/javascript/__resource.lua)

```lua
resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'
dependency 'webpack'
webpack_config 'client.config.js'
client_script 'dist/index.js'
```

I personally do not like this approach since the FiveM builder is slow (probably due to the worker stuff). If you want to build it using the FiveM builder, delete the `node_modules` folder and `package-lock.json` (if it's there) and just run your server.

If you want to build outside of your FiveM server install the [webpack-cli](https://webpack.js.org/api/cli/) and then build it with `webpack --config client.config.js`.

Now that I think of it... we may need to add `dependency 'yarn'` so that the npm packages install 🤔 

I'll do some testing.

**Comment by tarzasai** [comment]
Thanks for the answer, so I've installed webpack and webpack-cli as devDependencies, set a script in package.json to execute `webpack --config client.config.js` and I finally can try some scripting :)

**Comment by d0p3t** [comment]
> Thanks for the answer, so I've installed webpack and webpack-cli as devDependencies, set a script in package.json to execute `webpack --config client.config.js` and I finally can try some scripting :)

Glad you got it working. You can also check out my [fivem-ts-boilerplate](https://github.com/d0p3t/fivem-ts-boilerplate) as well as FiveM gamemode [aslt](https://github.com/thers/aslt) for more ways to work with node modules. I especially like the way that aslt does it. I use that webpack method almost exclusively, so I don't have to manually restart a resource while developing 😃

**Comment by tarzasai** [comment]
> fivem-ts-boilerplate

what is it, typescript definitions for the stuff in @citizenfx, native and universal and everything? I kinda need it but not sure if requires to npm-install something or what.

Edit: perhaps it's a template?

> aslt

I understand is the watch in webpack.js that does the trick, very interesting.
